/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CareersNewImport } from './routes/careers.new'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CareersNewRoute = CareersNewImport.update({
  id: '/careers/new',
  path: '/careers/new',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/careers/new': {
      id: '/careers/new'
      path: '/careers/new'
      fullPath: '/careers/new'
      preLoaderRoute: typeof CareersNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers/new': typeof CareersNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers/new': typeof CareersNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/careers/new': typeof CareersNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/careers/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/careers/new'
  id: '__root__' | '/' | '/careers/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersNewRoute: typeof CareersNewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersNewRoute: CareersNewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/careers/new"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/careers/new": {
      "filePath": "careers.new.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
